### PR TITLE
Format with rustfmt

### PR DESCRIPTION
**Pull request by grahamking**
So that my actual changes don't get mixed into the formatting.

### CODE REVIEW

**Comment by QEDK** [comment]
Thanks a lot, @grahamking Could you make the naming more semantic, like "Format with rustfmt"

**Comment by grahamking** [comment]
Sure can! I'll close this and open a different PR.

**Comment by grahamking** [comment]
OK, after some invasive branch surgery on my repo I think I have it all lined up. I've never submitted a PR that builds on another PR, so let me know if the second one (adding ':' support) is problematic. Thanks!

**Comment by QEDK** [comment]
> 
> 
> OK, after some invasive branch surgery on my repo I think I have it all lined up. I've never submitted a PR that builds on another PR, so let me know if the second one (adding ':' support) is problematic. Thanks!

The correct way to do this would be to make two different branches, so you can make your first commit and then checkout a new branch from that branch and make the next commit. Then, you can make the PRs and have it be dependent on one another.

**Comment by grahamking** [comment]
A branch of a branch, that makes a lot of sense, thanks. And sorry for the mess I made of your PRs. 

I'm porting [kip](https://github.com/grahamking/kip) to Rust (as an excuse to play with Rust). It uses INI files for config. I needed an INI parser with no dependencies, so I was very glad to find your project.

**Comment by QEDK** [comment]
> 
> 
> A branch of a branch, that makes a lot of sense, thanks. And sorry for the mess I made of your PRs.
> 
> I'm porting [kip](https://github.com/grahamking/kip) to Rust (as an excuse to play with Rust). It uses INI files for config. I needed an INI parser with no dependencies, so I was very glad to find your project.

That's pretty cool actually, I made this library as I was learning Rust and I found the current crates to have incomplete docs, so yeah. Glad to have you contribute! 😄

**Pull request closed without merging**
