### PR TITLE
 Allow ':' as delimiter, to match python version.

### PR DESCRIPTION
**Pull request by grahamking**
I have a previous pull request with just the formatting. After that one this change should be quite small. It adds a `delimiters` field on `Ini`, sets it like this `delimiters: vec!['=', ':'],` and then makes this change in the parsing:
```
-                None => match trimmed.find('=') {
+                None => match trimmed.find(&self.delimiters[..]) {
```

There's also a couple changes in tests/ to check it works.

### CODE REVIEW

**Comment by QEDK** [comment]
Hey @grahamking there's still a typo, can you just do the following rebase it with `git rebase -i HEAD~2` - This should bring up a screen with the last two commits you made on your master branch, then change the "pick" to "reword" for the typo commit and amend the commit message - and force-push it.
Let me know if you get stuck somewhere.

Sorry for this, I could do it myself but if I rebase the changes, you'll lose your authorship over the commits and I don't want that.

**Comment by grahamking** [comment]
That worked, thank you! I didn't know about that part of git.

**Review by QEDK — APPROVED** [review]
LGTM! 👍

**Comment by QEDK** [comment]
> 
> 
> That worked, thank you! I didn't know about that part of git.

Makes life much easier. 😉

**Pull request merged**
